### ISSUE TITLE
Few games stopped work after system update

### ISSUE THREAD

**Issue by gbschenkel** [ValveSoftware/steam-runtime#363]
#### Your system information

* Steam Runtime Version: 
* Distribution: **Slackware 14.2-current**
* [Full system information](https://gist.github.com/gbschenkel/dcf736695467bc8c00423812f2a0b030)
* Have you checked for system updates?: **Yes**
* Are you using the Steam Linux Runtime compatibility tool?: **No**

#### Please describe your issue in as much detail as possible:
I have tried to run _World of Warships_ and _Kingdom Come: Deliverance_ and both doesn't start, for shutdown I need kill the pressure-vessel to Steam return from "Running" state.
I have tested using client_beta and previous_release but both didn't work.
Also have deleted the pinned_libs to link any new libs which Steam have need but didn't work either.

I also have tried _Assassin's Creed Origins_, this one worked as should be.

[slr-app552990-s5c2158af4b578f2e.log](https://gist.github.com/gbschenkel/c289eda836b701a190aef0a9732d8eca)

#### Steps for reproducing this issue:

1. Open Steam
2. Run the game _World of Warships_ or _Kingdom Come: Deliverance_

PS: I saw two other issue about pressure_vessel, maybe is related.

**Comment by smcv** [comment]
>    "build_id" : "0.20210126.1",

This version of `SteamLinuxRuntime_soldier` has a known bug on some systems (#361, #362) and was pulled from the `client_beta` branch.

If you are seeing games getting stuck with the default (non-beta) branch of soldier, please could you get system information and a log with that version?

If you are finding that one game (like Assassin's Creed Origins) works, and another game (like World of Warships) gets stuck during setup, then it would also be useful to get a log from each game with nothing else changed, so we can compare them.

We often use [Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) and [Life Is Strange Episode 1](https://store.steampowered.com/app/319630/Life_is_Strange__Episode_1/) as test games. They're native Linux games, but if you force use of Proton 5.13 in the game's properties, Steam will download the Windows version.

Those games have the advantages that they're free-to-play (so everyone can compare them), available as native Linux games (so we can compare native with Proton), not too big (so they work on older hardware), and single-player (so we don't get anti-cheat mechanisms interfering with Proton).

**Comment by gbschenkel** [comment]
Okay, I will do it at night, right now I am at work.

**Comment by smcv** [comment]
Do you know which version of Proton you were using?

**Comment by smcv** [comment]
I can reproduce a similar hang with World of Warships, which seems to be related to Vulkan drivers getting duplicated in the container. A fix is in progress.

**Comment by gbschenkel** [comment]
Appears is the 5.13.5, is the default 5.13 from Steam. (I am still on the
work, but I think my system log maybe has the correct info)

**Comment by smcv** [comment]
We think this is fixed in the new `client_beta` update with pressure-vessel 0.20210203.0.

I was able to reproduce a similar problem with World of Warships, soldier 0.20210201.0 and Proton 5.13-5, and this updated soldier beta seems to fix it.

**Comment by gbschenkel** [comment]
I will try it in few hours with both games to check it.

**Comment by gbschenkel** [comment]
I tested, and didn't worked for me, still hangs.
[slr-app552990-sd18968207f0ef110.log](https://gist.github.com/gbschenkel/b5231989b43ed916ead1c8f51f10d514)

**Comment by smcv** [comment]
This looks like not the same bug as #361 and #362. Your log contains this, which I didn't see in the others:

```
preloader: Warning: failed to reserve range 00010000-00110000
esync: up and running.
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 00010000-00110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
WARNING: radv is not a conformant vulkan implementation, testing use only.
preloader: Warning: failed to reserve range 00010000-00110000
0/0: preloader: Warning: failed to reserve range 00010000-00110000
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2223) : Assertion Failed: V_strlen( pchInstallPath ) > 0
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
src\clientdll\installscript_win32.cpp (2224) : Assertion Failed: V_IsAbsolutePath( pchInstallPath )
```

**Comment by smcv** [comment]
Because it isn't immediately clear which component is going wrong here, it would be useful if you could capture a matching set (same versions of everything, without updating anything in between) of:

* Help -> System Information
* Steam Linux Runtime log (`slr-*.log` from `STEAM_LINUX_RUNTIME_LOG=1`)
* Proton log (`steam-*.log` from `PROTON_LOG=1`)

If you have a pair of scenarios where one works and the other doesn't, it would also be really useful to be able to compare that information from the working scenario and the non-working scenario.

For instance, if you have one game that works and one game that doesn't, you could collect: Help -> System Information; `slr-*.log` from working game; `steam-*.log` from working game; `slr-*.log` from non-working game; and `steam-*.log` from non-working game.

> stopped work after system update

Can you find out from your package manager which packages were updated during this system update?

As a Debian user, I'd use `/var/log/dpkg.log` and `/var/log/apt/` for this, but I don't know whether Slackware has an equivalent of those logs.

**Comment by RyuzakiKK** [comment]
> This looks like not the same bug as #361 and #362. Your log contains this, which I didn't see in the others:

From my testings with World of Warships it seems like the assertions failings are harmless, because I'm getting them too  and the game still runs. So the only part that is different is the beginning:
```
preloader: Warning: failed to reserve range 00010000-00110000
esync: up and running.
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 00010000-00110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
WARNING: radv is not a conformant vulkan implementation, testing use only.
preloader: Warning: failed to reserve range 00010000-00110000
0/0: preloader: Warning: failed to reserve range 00010000-00110000
```

**Comment by gbschenkel** [comment]
Well, I didn't found any libs been updated which could mess with the game:

```
calligra-3.2.1-x86_64-4
calligraplan-3.3.0-x86_64-1
digikam-7.1.0-x86_64-3
dosfstools-4.2-x86_64-1
dvdauthor-0.7.2-x86_64-3
e2fsprogs-1.46.0-x86_64-1
emacs-27.1-x86_64-4
fcitx-libpinyin-0.5.4-x86_64-1
gamin-0.1.10-x86_64-8
gd-2.3.1-x86_64-1
hwdata-0.344-noarch-1
ibus-m17n-1.4.4-x86_64-1
imagemagick-7.0.10_61-x86_64-1
kdev-php-5.6.2-x86_64-1
kdev-python-5.6.2-x86_64-1
kdevelop-5.6.2-x86_64-1
kfilemetadata-5.78.0-x86_64-3
kid3-3.8.5-x86_64-1
kile-2.9.93-x86_64-4
krb5-1.19-x86_64-1
krita-4.4.2-x86_64-2
libevdev-1.11.0-x86_64-1
libgcrypt-1.9.1-x86_64-1
libwacom-1.8-x86_64-1
libwebp-1.2.0-x86_64-1
mesa-20.3.4-x86_64-1
musescore-3.6.1-x86_64-1alien
nghttp2-1.43.0-x86_64-1
okteta-0.26.5-x86_64-1
oprofile-1.4.0-x86_64-5
poppler-21.02.0-x86_64-1
python-packaging-20.9-x86_64-1
python-pip-21.0.1-x86_64-1
python-setuptools-53.0.0-x86_64-1
samba-4.13.4-x86_64-2
sysklogd-2.2.1-x86_64-1
xine-lib-1.2.11-x86_64-3
xorriso-1.5.4-x86_64-1
xpdf-4.03-x86_64-1
```

After I tried the games and they didn't work, I have upgraded again my compat32 libs (32bits libs for Slackware64). The list is extensive. After that didn't work too, I have opened this issue. 

PS: I am working right now to create the logs for Floating Point(Proton vs Native), Life is Strange(Proton vs Native) and Assassin's Creed Origins(Proton).

**Comment by gbschenkel** [comment]
The game logs, all games working.
[Floating Point log](https://gist.github.com/gbschenkel/ec1eaeec8ac1d353f4490b190cd1d0d9)
[Life is Stranger](https://gist.github.com/gbschenkel/5591de74248ddfedbea799db3df5b1fd)
[Assassin's Creed Origin](https://gist.github.com/gbschenkel/bc2daf3901f68d7c9c542e47d22ce0fa)

**Comment by kisak-valve** [comment]
Hello @gbschenkel, can you test if temporarily disabling MangoHud with something like `sudo mv /usr/share/vulkan/implicit_layer.d/MangoHud.json /usr/share/vulkan/implicit_layer.d/MangoHud.json.disabled` has an effect?

**Comment by gbschenkel** [comment]
Shit, it opened. The problem is with mangohud... don't believe...

**Comment by kisak-valve** [comment]
Okay, so my hypothesis is that https://cgit.freedesktop.org/mesa/mesa/commit/?h=20.3&id=affb8eebe405854b93452eeca54b4ad0289542c2 lead to https://gitlab.freedesktop.org/mesa/mesa/-/issues/3801.

**Comment by smcv** [comment]
@kisak-valve, please could you retitle this to "bad interactions between Mesa 20.3.4, MangoHud and Steam Linux Runtime" to reflect our current understanding of what is going on here?

The list of known issues has more information on this, but the short version is that upgrading Mesa to 20.3.4 while using both MangoHud and Steam Linux Runtime can cause something to break. This can manifest as a crash, a freeze, games not starting or various other failure modes (it's undefined behaviour, so anything could happen).

I don't think this is really a bug in pressure-vessel or the Steam Linux Runtime, but for whatever reason, it seems like either the Steam Linux Runtime or Proton/DXVK triggers it more often than native games.

Mesa 20.3.5 and 21.0.0 have a workaround - or possibly a solution, nobody is really sure whose bug this is - so upgrading to one of those versions should hopefully resolve this.

We're continuing to look into whether this is a bug in Mesa, MangoHud, pressure-vessel, Vulkan-Loader or some other component. When we find out which, hopefully we can either solve it, or confirm that the Mesa changes are a correct solution.

**Comment by gbschenkel** [comment]
Hi @smcv I going to close this issue okay, I think after near 5 years this is not an issue anymore.
